### PR TITLE
Open SDG 0.5.0

### PR DESCRIPTION
**Pull request by brockfanning**
This upgrades to Open SDG 0.5.0 and adjusts a few layouts/translations/permalinks as needed.

### CODE REVIEW

**Comment by dawncomer** [comment]
PR committed @brockfanning

**Comment by dawncomer** [comment]
It looks like this one [failed](https://circleci.com/gh/dawncomer/open-sdg-site-starter/222)

**Comment by brockfanning** [comment]
@dawncomer Whoops, try this fix: #31

**Comment by dawncomer** [comment]
This worked @brockfanning

**Pull request merged**
